const ActionType = {
	START_LOADING: 'START_LOADING',
	FINISH_LOADING: 'FINISH_LOADING',
	SET_ACCOUNTS: 'SET_ACCOUNTS',
	SET_ACTIVE_ACCOUNT: 'SET_ACTIVE_ACCOUNT',
	SET_PREDICTION_MARKET_PROPERTIES: 'SET_CONTRACT_OWNER',
	SET_QUESTION: 'SET_QUESTION'
};

module.exports = ActionType;